### ISSUE TITLE
Setting K equal to 0 kill the cat badly

### ISSUE THREAD

**Issue by AlessandroSpallina** [Furrmidable-Crew/cat_advanced_tools#4]
**Describe the bug**
I lost my mind trying to understand why my cat was raising `'>=' not supported between instances of 'UnexpectedResponse' and 'int'`, after a while I understood was C.A.T. advanced tools' fault.

**To Reproduce**
1. Set Procedural Memory K = 0
2. Try to chat

**Additional context**
Using cat v1.5.1 with qdrant v1.7.1 and ollama v0.1.28.
Logs:
```
cheshire_cat_core           | [2024-03-14 17:25:09.286] INFO   cat.looking_glass.stray_cat.StrayCat.recall_relevant_memories_to_working_memory::121
cheshire_cat_core           | "Recall query: 'ooo'"
cheshire_cat_vector_memory  | 2024-03-14T17:25:10.437872Z  INFO actix_web::middleware::logger: 192.168.0.4 "POST /collections/episodic/points/search HTTP/1.1" 200 68 "-" "python-httpx/0.27.0" 0.002927
cheshire_cat_vector_memory  | 2024-03-14T17:25:10.441132Z  INFO actix_web::middleware::logger: 192.168.0.4 "POST /collections/declarative/points/search HTTP/1.1" 200 69 "-" "python-httpx/0.27.0" 0.000905 
cheshire_cat_vector_memory  | 2024-03-14T17:25:10.443311Z  INFO actix_web::middleware::logger: 192.168.0.4 "POST /collections/procedural/points/search HTTP/1.1" 422 131 "-" "python-httpx/0.27.0" 0.000355 
cheshire_cat_core           | [2024-03-14 17:25:10.444] ERROR  cat.looking_glass.stray_cat.StrayCat.__call__::250
cheshire_cat_core           | UnexpectedResponse()
cheshire_cat_core           | [2024-03-14 17:25:10.467] ERROR  cat.routes.websocket..websocket_endpoint::82
cheshire_cat_core           | TypeError("'>=' not supported between instances of 'UnexpectedResponse' and 'int'")
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/app/cat/looking_glass/stray_cat.py", line 248, in __call__
cheshire_cat_core           |     self.recall_relevant_memories_to_working_memory()
cheshire_cat_core           |   File "/app/cat/looking_glass/stray_cat.py", line 170, in recall_relevant_memories_to_working_memory
cheshire_cat_core           |     memories = vector_memory.recall_memories_from_embedding(**config)
cheshire_cat_core           |   File "/app/cat/memory/vector_memory_collection.py", line 231, in recall_memories_from_embedding
cheshire_cat_core           |     memories = self.client.search(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_client.py", line 343, in search
cheshire_cat_core           |     return self._client.search(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/qdrant_remote.py", line 479, in search
cheshire_cat_core           |     search_result = self.http.points_api.search_points(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 1388, in search_points
cheshire_cat_core           |     return self._build_for_search_points(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api/points_api.py", line 636, in _build_for_search_points
cheshire_cat_core           |     return self.api_client.request(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 74, in request
cheshire_cat_core           |     return self.send(request, type_)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/qdrant_client/http/api_client.py", line 97, in send
cheshire_cat_core           |     raise UnexpectedResponse.for_response(response)
cheshire_cat_core           | qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 422 (Unprocessable Entity)
cheshire_cat_core           | Raw response content:
cheshire_cat_core           | b'{"status":{"error":"Validation error in JSON body: [search_request.limit: value 0 invalid, must be 1.0 or larger]"},"time":0.0}'
cheshire_cat_core           |
cheshire_cat_core           | During handling of the above exception, another exception occurred:
cheshire_cat_core           |
cheshire_cat_core           | Traceback (most recent call last):
cheshire_cat_core           |   File "/app/cat/routes/websocket.py", line 73, in websocket_endpoint
cheshire_cat_core           |     await asyncio.gather(
cheshire_cat_core           |   File "/app/cat/routes/websocket.py", line 24, in receive_message
cheshire_cat_core           |     cat_message = await run_in_threadpool(stray.run, user_message)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
cheshire_cat_core           |     return await anyio.to_thread.run_sync(func, *args)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
cheshire_cat_core           |     return await get_asynclib().run_sync_in_worker_thread(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
cheshire_cat_core           |     return await future
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
cheshire_cat_core           |     result = context.run(func, *args)
cheshire_cat_core           |   File "/app/cat/looking_glass/stray_cat.py", line 340, in run
cheshire_cat_core           |     return self.loop.run_until_complete(
cheshire_cat_core           |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
cheshire_cat_core           |   File "/app/cat/looking_glass/stray_cat.py", line 251, in __call__
cheshire_cat_core           |     traceback.print_exc(e)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/traceback.py", line 179, in print_exc
cheshire_cat_core           |     print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/traceback.py", line 119, in print_exception
cheshire_cat_core           |     te = TracebackException(type(value), value, tb, limit=limit, compact=True)
cheshire_cat_core           |   File "/usr/local/lib/python3.10/site-packages/exceptiongroup/_formatting.py", line 96, in __init__
cheshire_cat_core           |     self.stack = traceback.StackSummary.extract(
cheshire_cat_core           |   File "/usr/local/lib/python3.10/traceback.py", line 357, in extract
cheshire_cat_core           |     if limit >= 0:
cheshire_cat_core           | TypeError: '>=' not supported between instances of 'UnexpectedResponse' and 'int'
cheshire_cat_core           | INFO:     connection closed
```

**Comment by nicola-corbellini** [comment]
Fixed updating the field validator to not allow values `<=0`
